### ISSUE TITLE
Many tags on small screen won't break off to second line 

### ISSUE THREAD

**Issue by iroQuai** [nightswinger/hugo-theme-coyote#11]
First of all: what a nice theme! I decided to use it for a personal recipe collection site im building.  I love how the site is responsive but still keeps two columns on phone screens. 

Now one thing I noticed: when adding several tags to a post, it doesn't look that good viewing the post on a small screen (like mobile phones). The line of tags doesn't break into a second line!

Live example: https://recepten.stijnbiemans.nl/recepten/falafelbowl-met-hummus-en-feta/. 

Screenshot:
![Screenshot_20230209_195328_Vivaldi Browser](https://user-images.githubusercontent.com/7004624/217909830-c068415b-5021-49fa-bd2b-b3c70d5bc2f9.jpg)

**Comment by nightswinger** [comment]
Thanks for the report.
I will fix it soon.
