### ISSUE TITLE
Search only matches exact left-to-right ordered terms

### ISSUE THREAD

**Issue by AligningEntropy** [nightswinger/hugo-theme-coyote#4]
# Current State / Issue
Presently, when using this theme locally and on the deployed [exampleSite](https://nightswinger.github.io/hugo-theme-coyote/search/?), the search function appears to only work if the search terms are in the same exact left-to-right order as the target.

For example, the article "Markdown Syntax Guide" is ONLY discoverable by searching for:
- "Markdown"
- "Markdown Syntax"
- "Markdown Syntax Guide"

All other patterns fail to return any result.

This forces the user to be able to recall the left-to-right order of terms to search for the respective post. Additionally, it prevents discoverability of posts that share a common postfix name (ex: Markdown-Guide, Image-Guide, etc.).

# Expected
When fuzzy searching for an article any enumeration of the search terms should be viable.

For example, the article "Markdown Syntax Guide" should be discoverable by searching for:
- "Markdown"
- "Syntax"
- "Guide"
- "Syntax Guide"
- "Markdown Syntax"
- "Markdown Guide"
- "Markdown Syntax Guide"

# Further thoughts
The `index.json` appears to be generated as expected which makes me think that it has something to do with the `fuse.search` call in [search.js](https://github.com/nightswinger/hugo-theme-coyote/blob/main/assets/js/search.js#L31) and / or the `fuseOptions` options specified in [search.js](https://github.com/nightswinger/hugo-theme-coyote/blob/main/assets/js/search.js#L2)

**Comment by nightswinger** [comment]
you are right.
current behavior is strange.
I will look into fuse.js options.
thanks.
