### ISSUE TITLE
Search clears when the user presses Enter/Return

### ISSUE THREAD

**Issue by AligningEntropy** [nightswinger/hugo-theme-coyote#5]
# Current State / Issue
Presently, when using this theme locally and on the deployed [exampleSite](https://nightswinger.github.io/hugo-theme-coyote/search/?), when the user types in a search query and presses `Enter` the search and its results are cleared before the user can use them.

# Expected
The results should persist / remain visible following the pressing of `Enter`.

# Further thoughts
The current behavior uses an `addEventListener` in [search.js](https://github.com/nightswinger/hugo-theme-coyote/blob/main/assets/js/search.js#L30) that actions on `keyup`.

This could potentially be modified to use something that checks for if the `Enter` key was pressed and then holds the current view.
Ex: 
```
...addEventListener('keypress', function (e) {
    if (e.key === 'Enter') {
      // do nothing / hold current view
    } else {
     // current code for search
    }
});
```

**Comment by nightswinger** [comment]
thanks for report.
I've identified a behavior and it will be fixed in next release.
