### ISSUE TITLE
Search result not showing

### ISSUE THREAD

**Issue by jere168** [nightswinger/hugo-theme-coyote#9]
Search result not showing, how to fix this? i try on localhost. please any documentation or guide ?
i love this theme......

**Comment by nightswinger** [comment]
Thanks for using this theme.

I also tried it and it is showing up fine.
can you tell me how I can reproduce it?

**Comment by jere168** [comment]
ok.. search working.. by adding in config.toml
`[outputs]
  home = ['HTML', 'JSON']`
